[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld", # Pass custom linker script to Rust
    "-C", "code-model=kernel",     # Ensure memory addresses fit kernel space
]