BUILDLOC = ../Build
LIBLOC   = ../Lib/HAL

all: 
	$(MAKE) -C LibIDT/
	$(MAKE) -C LibHAL/

clean:
	rm -f $(BUILDLOC)/*.o
	rm -f $(BUILDLOC)/*.bin
	rm -f $(BUILDLOC)/*.img
	rm -f $(LIBLOC)/*.a
	rm -f $(LIBLOC)/*.so
